spring.application.name=ms-envios
server.port=8083

# Configuración de Base de Datos
spring.datasource.url=jdbc:h2:mem:enviosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Configuración de Kafka (Necesaria para escuchar pedidos confirmados)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=envios-group
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Evita que la app falle si Kafka no está disponible al arrancar
spring.kafka.admin.fail-fast=false
# Permite que los Listeners esperen a que el tópico exista en lugar de fallar
spring.kafka.listener.missing-topics-fatal=false

spring.kafka.producer.properties.max.block.ms=5000